version: "3.8"

services:
  airsim-swarm-dev:
    build: .
    container_name: airsim-swarm-dev
    volumes:
      - ./:/home/devuser/airsim-swarm
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: "host"
    stdin_open: true
    tty: true
    user: "${USER_ID:-devuser}"
