services:
  px4:
    build: .
    container_name: airsim-px4
    network_mode: host
    environment:
      - PX4_AUTOSTART=1
    volumes:
      - ./:/home/devuser/airsim-swarm
    working_dir: /home/devuser/airsim-swarm
    stdin_open: true
    tty: true
