version: "3.8"
services:
  airsim-swarm-dev:
    build: .
    container_name: airsim-swarm-dev
    volumes:
      - ./:/home/devuser/airsim-swarm
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
